version: '3'

services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: qwertz
            MYSQL_DATABASE: products
        ports:
        - "3306:3306"
        volumes:
        - ./data/fixtures/database.sql:/docker-entrypoint-initdb.d/database.sql
